version: 3
endpoint: http://localhost:8080
admin_secret: admin_secret_for_testing
metadata_directory: ./metadata
migrations_directory: ./migrations
seeds_directory: seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
